# Generated by Django 4.2.4 on 2023-09-20 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=30)),
                ('autor', models.CharField(default='', max_length=30)),
                ('image', models.ImageField(upload_to='./images')),
                ('genero', models.CharField(choices=[('1', 'Aventura'), ('2', 'Terror'), ('3', 'Romance'), ('4', 'Poesia'), ('5', 'Fantasia'), ('6', 'Biografia'), ('7', 'Autobiografia')], default='1', max_length=20)),
                ('status', models.CharField(choices=[('1', 'Disponível'), ('2', 'Alugado')], default='1', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_Ret', models.DateTimeField(default=datetime.datetime(2023, 9, 20, 22, 15, 20, 904345, tzinfo=datetime.timezone.utc))),
                ('data_Dev', models.DateTimeField(default=datetime.datetime(2023, 9, 20, 22, 15, 20, 904345, tzinfo=datetime.timezone.utc))),
                ('status', models.CharField(choices=[('1', 'Pendente'), ('2', 'Atrasado'), ('3', 'Entregue')], default='1', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=40)),
                ('cpf', models.CharField(default='', max_length=11)),
                ('telefone', models.CharField(default='4002-8922', max_length=14)),
                ('senha', models.CharField(default='', max_length=40)),
                ('endereco', models.TextField(default='', max_length=255)),
                ('ficha', models.CharField(choices=[('1', 'Limpa'), ('2', 'Punição')], default='1', max_length=20)),
            ],
        ),
    ]
