# Generated by Django 4.2.4 on 2023-09-20 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='data_Dev',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 22, 19, 52, 995537, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='registro',
            name='data_Ret',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 22, 19, 52, 995537, tzinfo=datetime.timezone.utc)),
        ),
    ]
