# Generated by Django 4.2.4 on 2023-09-20 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_alter_registro_data_dev_alter_registro_data_ret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='data_Dev',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 19, 25, 22, 469233)),
        ),
        migrations.AlterField(
            model_name='registro',
            name='data_Ret',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 19, 25, 22, 469233)),
        ),
    ]
