# Generated by Django 4.2.4 on 2023-09-20 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_alter_registro_data_dev_alter_registro_data_ret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='titulo',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='livros',
            name='ano',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='livros',
            name='genero',
            field=models.CharField(choices=[('1', 'Aventura'), ('2', 'Terror'), ('3', 'Romance'), ('4', 'Poesia'), ('5', 'Fantasia'), ('6', 'Biografia'), ('7', 'Drama')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='registro',
            name='data_Dev',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 20, 22, 48, 57703)),
        ),
        migrations.AlterField(
            model_name='registro',
            name='data_Ret',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 20, 22, 48, 57703)),
        ),
    ]
