# Generated by Django 4.2.4 on 2023-09-26 00:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_genero_delete_registro_livros_destaque_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_Ret', models.DateTimeField(default=datetime.datetime(2023, 9, 25, 21, 4, 26, 895695))),
                ('data_Dev', models.DateTimeField(default=datetime.datetime(2023, 9, 25, 21, 4, 26, 895695))),
                ('status', models.CharField(choices=[('1', 'Pendente'), ('2', 'Atrasado'), ('3', 'Entregue')], default='1', max_length=20)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.livros')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.usuario')),
            ],
        ),
    ]
