# Generated by Django 4.2.5 on 2023-10-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0008_feedback_alter_registro_data_dev_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='data_Dev',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='registro',
            name='data_Ret',
            field=models.CharField(max_length=45),
        ),
    ]
